status = [
    "Build on ubuntu-22.04 (x86_64-unknown-linux-gnu)",
    "Build on ubuntu-22.04 (x86_64-unknown-linux-musl)",
    "Build on ubuntu-22.04 (i686-unknown-linux-gnu)",
    "Build on ubuntu-22.04 (i686-unknown-linux-musl)",
    "Build on ubuntu-22.04 (aarch64-unknown-linux-gnu)",
    "Build on ubuntu-22.04 (aarch64-unknown-linux-musl)",
    "Build on ubuntu-22.04 (armv5te-unknown-linux-gnueabi)",
    "Build on ubuntu-22.04 (armv7-unknown-linux-gnueabihf)",
    "Build on ubuntu-22.04 (arm-unknown-linux-gnueabi)",
    "Build on ubuntu-22.04 (arm-unknown-linux-gnueabihf)",
    "Build on windows-2022 (x86_64-pc-windows-msvc)",
    "Build on windows-2022 (aarch64-pc-windows-msvc)",
    "Build on macos-11 (x86_64-apple-darwin)",
    "Build on macos-11 (aarch64-apple-darwin)",
    "Test",
    "Lint",
]
required_approvals = 1
up_to_date_approvals = true
delete_merged_branches = true
update_base_for_deletes = true
use_codeowners = true
cut_body_after = "<details>"
commit_title = "chore(pull): merge ${PR_REFS}"
