# configuration for https://github.com/orhun/halp

# check the version flag
check_version = false
# check the help flag
check_help = false
# arguments to check
check = [ [ "-v", "-V", "--version" ], [ "-h", "--help", "help", "-H" ] ]
# command to run for manual pages
man_command = "man"
# pager to use for command outputs
pager_command = "less -R"
